apiVersion: demo.golearning.dev/v1alpha1
kind: Kluster
metadata:
  labels:
    app.kubernetes.io/name: kluster
    app.kubernetes.io/instance: kluster-sample
    app.kubernetes.io/part-of: kubebuilder-kluster
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-kluster
  name: kluster-sample-1
spec:
  name: kluster-sample-1
  region: "blr1"
  version: "1.23.10-do.0"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 1
      name: "dummy-nodepool"
      size: "s-1vcpu-2gb"
